# Generated by Django 3.1.5 on 2021-01-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Its all about code click to view', max_length=255),
        ),
    ]
